name: synopse
description: "We serve up bite-sized, unbiased news nuggets."

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  audio_video_progress_bar: ^2.0.1
  bloc_concurrency: ^0.2.3
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.1
  device_preview: ^1.1.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  firebase_analytics: ^10.8.6
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.1
  flutter_bloc: ^8.1.3
  flutter_card_swiper: ^7.0.0
  flutter_native_splash: ^2.3.10
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  go_router: ^13.1.0
  google_mobile_ads: ^4.0.0
  google_sign_in: ^6.2.1
  graphql_flutter: ^5.1.2
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  logging: ^1.2.0
  permission_handler: ^11.2.0
  rename: ^3.0.1
  rxdart: ^0.27.7
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  webview_flutter: ^4.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# git add . && git commit -m "initial commit" && git push origin main
# dart run build_runner watch --delete-conflicting-outputs
# dart run build_runner build --delete-conflicting-outputs
# cd android
# flutter build apk --split-per-abi
# flutter pub global activate rename
# dart run rename setAppName -v synopse
# dart run rename setBundleId -v com.synopseai.synopse
# dart run flutter_native_splash:create
# adb shell am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d https://synopse-ai.web.app/dd/456
flutter_native_splash:
  color: "#35393A"
  image: assets/images/splash.png
  android: true
  ios: true
  web: true

# dart run flutter_launcher_icons
# gradlew signInReport
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: AllianceNo2
      fonts:
        - asset: assets/fonts/AllianceNo2-Light.ttf
          weight: 300
        - asset: assets/fonts/AllianceNo2-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/AllianceNo2-Regular.ttf
          weight: 400
        - asset: assets/fonts/AllianceNo2-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/AllianceNo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/AllianceNo2-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/AllianceNo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AllianceNo2-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/AllianceNo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/AllianceNo2-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AllianceNo2-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AllianceNo2-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/AllianceNo2-Black.ttf
          weight: 900
        - asset: assets/fonts/AllianceNo2-BlackItalic.ttf
          weight: 900
          style: italic
