name: rss1_v3
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0-42.1.beta <4.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  go_router: ^10.1.2
  graphql_flutter: ^5.1.2
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  like_button: ^2.0.5
  logging: ^1.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  transparent_image: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  intl_utils: ^2.8.4

# dart run build_runner watch --delete-conflicting-outputs
flutter_gen:
  output: lib/core/asset_gen/
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  arb_dir: lib/core/l10n
  output_dir: lib/core/generated

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#f3f6f4"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cabin Condensed
      fonts:
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-Medium.ttf
          weight: 500
