name: synopse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.8
  go_router: ^12.0.0
  google_sign_in: ^6.1.5
  graphql_flutter: ^5.1.2
  http: ^1.1.0
  meta: ^1.9.1
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.4
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.5

# dart run build_runner watch --delete-conflicting-outputs
# dart run build_runner build --delete-conflicting-outputs
flutter_gen:
  output: lib/core/asset_gen/
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  arb_dir: lib/core/l10n
  output_dir: lib/core/generated

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#f3f6f4"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya/Alegreya-Regular.ttf
          weight: 400
        - asset: assets/fonts/Alegreya/Alegreya-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Alegreya/Alegreya-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alegreya/Alegreya-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Alegreya/Alegreya-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Alegreya/Alegreya-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Alegreya/Alegreya-Bold.ttf
          weight: 700
        - asset: assets/fonts/Alegreya/Alegreya-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Alegreya/Alegreya-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Alegreya/Alegreya-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Alegreya/Alegreya-Black.ttf
          weight: 900
        - asset: assets/fonts/Alegreya/Alegreya-BlackItalic.ttf
          weight: 900
          style: italic
