// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI8rx2fVzxjG5QYLRZf36gbGTW2awYSqc',
    appId: '1:375245301225:web:11134c90c7d59145269778',
    messagingSenderId: '375245301225',
    projectId: 'synopse-ai',
    authDomain: 'synopse-ai.firebaseapp.com',
    storageBucket: 'synopse-ai.appspot.com',
    measurementId: 'G-V21W7RK0TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvkxsKzrP5MqM1Xq06ng-QxYgqoarpQeE',
    appId: '1:375245301225:android:19bfabadb141c13d269778',
    messagingSenderId: '375245301225',
    projectId: 'synopse-ai',
    storageBucket: 'synopse-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7iDzztSoEIZxYQJRszxN0ITPtdF8P3LI',
    appId: '1:375245301225:ios:34e67efb4d840e14269778',
    messagingSenderId: '375245301225',
    projectId: 'synopse-ai',
    storageBucket: 'synopse-ai.appspot.com',
    iosBundleId: 'com.synopseai.synopse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7iDzztSoEIZxYQJRszxN0ITPtdF8P3LI',
    appId: '1:375245301225:ios:34e67efb4d840e14269778',
    messagingSenderId: '375245301225',
    projectId: 'synopse-ai',
    storageBucket: 'synopse-ai.appspot.com',
    iosBundleId: 'com.synopseai.synopse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI8rx2fVzxjG5QYLRZf36gbGTW2awYSqc',
    appId: '1:375245301225:web:338a1a29e63d8334269778',
    messagingSenderId: '375245301225',
    projectId: 'synopse-ai',
    authDomain: 'synopse-ai.firebaseapp.com',
    storageBucket: 'synopse-ai.appspot.com',
    measurementId: 'G-23NTMWL4SX',
  );

}