// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-8xM0sxlkDBsWnHdomcx6vjUApQb3nk',
    appId: '1:419429345645:web:7256c998da28de9ae31264',
    messagingSenderId: '419429345645',
    projectId: 'synopse-1edd7',
    authDomain: 'synopse-1edd7.firebaseapp.com',
    storageBucket: 'synopse-1edd7.appspot.com',
    measurementId: 'G-4EZWRESH26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApj8DKyrT23Ek2h9Tqp8eTeyp4IA3VnJI',
    appId: '1:419429345645:android:112e965732020b09e31264',
    messagingSenderId: '419429345645',
    projectId: 'synopse-1edd7',
    storageBucket: 'synopse-1edd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuKanePVvP7DOfcGjhjnjJ0DHMDoZoLkY',
    appId: '1:419429345645:ios:ab0c412167d2f5e1e31264',
    messagingSenderId: '419429345645',
    projectId: 'synopse-1edd7',
    storageBucket: 'synopse-1edd7.appspot.com',
    iosBundleId: 'com.synopse.synopse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuKanePVvP7DOfcGjhjnjJ0DHMDoZoLkY',
    appId: '1:419429345645:ios:8757bd340d0d6499e31264',
    messagingSenderId: '419429345645',
    projectId: 'synopse-1edd7',
    storageBucket: 'synopse-1edd7.appspot.com',
    iosBundleId: 'com.synopse.synopse.RunnerTests',
  );
}
