name: synopse
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  aad_oauth: ^1.0.0
  bloc_concurrency: ^0.2.3
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  device_preview: ^1.1.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  go_router: ^13.0.1
  google_mobile_ads: ^4.0.0
  google_sign_in: ^6.2.1
  graphql_flutter: ^5.1.2
  http: ^1.1.2
  image_picker: ^1.0.6
  intl: ^0.18.1
  permission_handler: ^11.1.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  webview_flutter: ^4.4.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter

# git add . && git commit -m "initial commit" && git push origin main
# dart run build_runner watch --delete-conflicting-outputs
# dart run build_runner build --delete-conflicting-outputs
# cd android
# flutter build apk --split-per-abi
flutter_gen:
  output: lib/core/asset_gen/
  integrations:
    flutter_svg: true

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#f3f6f4"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true

# dart run flutter_launcher_icons
# gradlew signInReport
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app.png"
  remove_alpha_ios: true

flutter:
  # generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Spectral-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Spectral-Light.ttf
          weight: 300
        - asset: assets/fonts/Spectral-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Spectral-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spectral-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Spectral-Medium.ttf
          weight: 500
        - asset: assets/fonts/Spectral-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Spectral-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Spectral-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Spectral-Bold.ttf
          weight: 700
        - asset: assets/fonts/Spectral-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Spectral-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Spectral-ExtraBoldItalic.ttf
          weight: 800
          style: italic
