name: synopse_v002
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  animations: ^2.0.8
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  go_router: ^11.1.2
  graphql_flutter: ^5.1.2
  http: ^1.1.0
  pinput: ^3.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  webview_flutter: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  intl_utils: ^2.8.4

# dart run build_runner watch --delete-conflicting-outputs
flutter_gen:
  output: lib/core/asset_gen/
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  arb_dir: lib/core/l10n
  output_dir: lib/core/generated

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#f3f6f4"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cabin Condensed
      fonts:
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-Bold.ttf
          weight: 700
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Bold.ttf
          weight: 700
    - family: Saira Condensed
      fonts:
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Black.ttf
          weight: 900
