name: synopse
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  aad_oauth: ^1.0.0
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  device_preview: ^1.1.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.8
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  go_router: ^12.0.1
  google_mobile_ads: ^4.0.0
  google_sign_in: ^6.1.5
  graphql_flutter: ^5.1.2
  http: ^1.1.0
  image_picker: ^1.0.5
  intl: ^0.18.1
  permission_handler: ^11.1.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  webview_flutter: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

# git add . && git commit -m "initial commit" && git push origin main
# dart run build_runner watch --delete-conflicting-outputs
# dart run build_runner build --delete-conflicting-outputs
# cd android
# flutter build apk --split-per-abi
flutter_gen:
  output: lib/core/asset_gen/
  integrations:
    flutter_svg: true

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#f3f6f4"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true

# dart run flutter_launcher_icons
# gradlew signInReport
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Noto Serif
      fonts:
        - asset: assets/fonts/NotoSerif-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSerif-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NotoSerif-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSerif-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NotoSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSerif-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NotoSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSerif-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NotoSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSerif-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NotoSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSerif-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSerif-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSerif-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSerif-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSerif-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSerif-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Noto Serif Condensed
      fonts:
        - asset: assets/fonts/NotoSerif_Condensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSerif_Condensed-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NotoSerif_Condensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSerif_Condensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NotoSerif_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSerif_Condensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NotoSerif_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSerif_Condensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NotoSerif_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSerif_Condensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NotoSerif_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSerif_Condensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NotoSerif_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSerif_Condensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSerif_Condensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSerif_Condensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSerif_Condensed-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSerif_Condensed-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Noto Serif SemiCondensed
      fonts:
        - asset: assets/fonts/NotoSerif_SemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSerif_SemiCondensed-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NotoSerif_SemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSerif_SemiCondensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NotoSerif_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSerif_SemiCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NotoSerif_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSerif_SemiCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NotoSerif_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSerif_SemiCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NotoSerif_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSerif_SemiCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NotoSerif_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSerif_SemiCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSerif_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSerif_SemiCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSerif_SemiCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSerif_SemiCondensed-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Noto Serif ExtraCondensed
      fonts:
        - asset: assets/fonts/NotoSerif_ExtraCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSerif_ExtraCondensed-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NotoSerif_ExtraCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSerif_ExtraCondensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NotoSerif_ExtraCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSerif_ExtraCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NotoSerif_ExtraCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSerif_ExtraCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NotoSerif_ExtraCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSerif_ExtraCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NotoSerif_ExtraCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSerif_ExtraCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NotoSerif_ExtraCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSerif_ExtraCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSerif_ExtraCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSerif_ExtraCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSerif_ExtraCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSerif_ExtraCondensed-BlackItalic.ttf
          weight: 900
          style: italic
