// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI8rx2fVzxjG5QYLRZf36gbGTW2awYSqc',
    appId: '1:375245301225:web:6fdc8a6f3f4521d2269778',
    messagingSenderId: '375245301225',
    projectId: 'synopse-ai',
    authDomain: 'synopse-ai.firebaseapp.com',
    storageBucket: 'synopse-ai.appspot.com',
    measurementId: 'G-RQR0TBRYSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvkxsKzrP5MqM1Xq06ng-QxYgqoarpQeE',
    appId: '1:375245301225:android:2435ef3a9a848ea8269778',
    messagingSenderId: '375245301225',
    projectId: 'synopse-ai',
    storageBucket: 'synopse-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7iDzztSoEIZxYQJRszxN0ITPtdF8P3LI',
    appId: '1:375245301225:ios:dedb45ede7e7644f269778',
    messagingSenderId: '375245301225',
    projectId: 'synopse-ai',
    storageBucket: 'synopse-ai.appspot.com',
    iosBundleId: 'com.synopse.synopse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7iDzztSoEIZxYQJRszxN0ITPtdF8P3LI',
    appId: '1:375245301225:ios:b7d21384c171c0fd269778',
    messagingSenderId: '375245301225',
    projectId: 'synopse-ai',
    storageBucket: 'synopse-ai.appspot.com',
    iosBundleId: 'com.synopse.synopse.RunnerTests',
  );
}
