name: rss1_v3
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  fimber: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.3.1
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  injectable: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.3.0

# dart run build_runner watch --delete-conflicting-outputs
flutter_native_splash:
  color: "#f3f6f4"
  image: assets/splash_screen/logo.png
  android: true
  ios: true
  web: true

flutter_gen:
  output: lib/core/asset_gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/splash_screen/
  fonts:
    - family: Cabin Condensed
      fonts:
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin_Condensed/CabinCondensed-Bold.ttf
          weight: 700
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Bold.ttf
          weight: 700
    - family: Saira Condensed
      fonts:
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Saira_Condensed/SairaCondensed-Black.ttf
          weight: 900
